# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: 1b922a3a-md-normal
  namespace: 1b922a3a
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: worker
